name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '4.7.1'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Archive build artifacts
        run: |
          mkdir artifacts
          copy .\BeeByteCleaner\bin\Release\BeeByteCleaner.exe artifacts\BeeByteCleaner.exe

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BeeByteCleaner
          path: artifacts

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: artifacts/BeeByteCleaner.exe
          token: ${{ secrets.ACTIONS_TOKEN }}